from PyQt6 import QtCore, QtGui, QtWidgets
from initialConfigScreenOne import Ui_InitConfScreenOne

class Ui_InitConfMain(object):
    def setupUi(self, InitConfMain):
        InitConfMain.setObjectName("InitConfMain")
        InitConfMain.resize(1920, 1080)
        InitConfMain.setStyleSheet("background-color: black;")
        self.line_5 = QtWidgets.QFrame(parent=InitConfMain)
        self.line_5.setGeometry(QtCore.QRect(1400, 10, 511, 21))
        self.line_5.setStyleSheet("background-color: gray;")
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_4 = QtWidgets.QFrame(parent=InitConfMain)
        self.line_4.setGeometry(QtCore.QRect(10, 1020, 1901, 21))
        self.line_4.setStyleSheet("background-color: gray;")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QFrame(parent=InitConfMain)
        self.line_3.setGeometry(QtCore.QRect(1890, 10, 21, 1031))
        self.line_3.setStyleSheet("background-color: gray")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QFrame(parent=InitConfMain)
        self.line_2.setGeometry(QtCore.QRect(10, 10, 21, 1031))
        self.line_2.setStyleSheet("background-color: gray")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(parent=InitConfMain)
        self.line.setGeometry(QtCore.QRect(10, 10, 521, 21))
        self.line.setStyleSheet("background-color: gray;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=InitConfMain)
        self.label.setGeometry(QtCore.QRect(550, 10, 831, 51))
        font = QtGui.QFont()
        font.setFamily("TI-92p Mini Sans")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("color: gray;")
        self.label.setObjectName("label")
        self.AdminControlsButton = QtWidgets.QPushButton(parent=InitConfMain)
        self.AdminControlsButton.setGeometry(QtCore.QRect(80, 80, 431, 41))
        self.AdminControlsButton.setStyleSheet("color: white;\n"
"font: 28pt \"TI-92p Mini Sans\";")
        self.AdminControlsButton.setObjectName("AdminControlsButton")
        self.AddUserButton = QtWidgets.QPushButton(parent=InitConfMain)
        self.AddUserButton.setGeometry(QtCore.QRect(80, 160, 281, 41))
        self.AddUserButton.setStyleSheet("color: white;\n"
"font: 28pt \"TI-92p Mini Sans\";")
        self.AddUserButton.setObjectName("AddUserButton")
        self.AccessiblilityButton = QtWidgets.QPushButton(parent=InitConfMain)
        self.AccessiblilityButton.setGeometry(QtCore.QRect(80, 240, 411, 41))
        self.AccessiblilityButton.setStyleSheet("color: white;\n"
"font: 28pt \"TI-92p Mini Sans\";")
        self.AccessiblilityButton.setObjectName("AccessiblilityButton")
        self.line.raise_()
        self.line_5.raise_()
        self.line_4.raise_()
        self.line_3.raise_()
        self.line_2.raise_()
        self.label.raise_()
        self.AdminControlsButton.raise_()
        self.AddUserButton.raise_()
        self.AccessiblilityButton.raise_()
        self.InitConfScreenOneButton = QtWidgets.QPushButton(parent=InitConfMain)

        self.retranslateUi(InitConfMain)
        QtCore.QMetaObject.connectSlotsByName(InitConfMain)

        #self.button.clicked.connect(self.goToInitConfMain)

    def retranslateUi(self, InitConfMain):
        _translate = QtCore.QCoreApplication.translate
        InitConfMain.setWindowTitle(_translate("InitConfMain", "Form"))
        self.label.setText(_translate("InitConfMain", "First Time Setup Sequence"))
        self.AdminControlsButton.setText(_translate("InitConfMain", "- Admin Controls"))
        self.AddUserButton.setText(_translate("InitConfMain", "- Add User"))
        self.AccessiblilityButton.setText(_translate("InitConfMain", "- Accessibility"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     InitConfMain = QtWidgets.QWidget()
#     ui = Ui_InitConfMain()
#     ui.setupUi(InitConfMain)
#     InitConfMain.show()
#     sys.exit(app.exec())
